In [4]:
# 1. fixed-length planning
# a cost to go

import numpy as np

def backward_value_iteration(k, G):
  # G의 k번째행에서 시작
  # k-1번째 행에서 0이 아니라면 그래프에서 그 점으로 갈 수 있는 점을 모두 검사
  # 각 점에서 k-1로 갈 수 있는 점들과 그 비용을 k번째 행에 계산하여 넣어줌

  num_city = len(cost4transition[0])

  for current_city in range(num_city):
    if G[k-1, current_city] != np.inf:
        for prev_city in range(num_city):
            if cost4transition[prev_city, current_city] != np.inf:
              G[k, prev_city] = min(
                G[k, prev_city],
                G[k-1, current_city] + cost4transition[prev_city, current_city]
                )

  return G

def func_cost_to_go(end_point, fixed_point):
  # Initialization
  num_city = len(cost4transition[0])
  G = np.full((fixed_length, num_city), np.inf)
  G[0, goal] = 0
  for k in range(1, fixed_point):
    print(G)
    print()
    G = backward_value_iteration(k, G)

  return G


a, b, c, d, e = 0, 1, 2, 3, 4
goal = b
fixed_length =6


cost4transition = np.zeros((5,5))
cost4transition[:,:] = np.inf
cost4transition[a,a]=2
cost4transition[a,b]=2
cost4transition[b,c]=1
cost4transition[b,d]=4
cost4transition[c,a]=1
cost4transition[c,d]=1
cost4transition[d,c]=1
cost4transition[d,e]=1

num_city = len(cost4transition[0])
G = np.full((fixed_length, fixed_length), np.inf)
G[0, 3] = 0

G = func_cost_to_go(goal, fixed_length)
print(G)




[[inf  0. inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [ 2. inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [ 2. inf inf inf inf]
 [ 4. inf  3. inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [ 2. inf inf inf inf]
 [ 4. inf  3. inf inf]
 [ 6.  4.  5.  4. inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [ 2. inf inf inf inf]
 [ 4. inf  3. inf inf]
 [ 6.  4.  5.  4. inf]
 [ 6.  6.  5.  6. inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [ 2. inf inf inf inf]
 [ 4. inf  3. inf inf]
 [ 6.  4.  5.  4. inf]
 [ 6.  6.  5.  6. inf]
 [ 8.  6.  7.  6. inf]]


In [2]:
import numpy as np

def forward_value_iteration(k, C):
#k-1에서 k번쨰로 이동할 떄, 그떄의 가격이 min인것으로.
  num_city = len(cost4transition[0])

  for current_city in range(num_city):
    if C[k-1, current_city] != np.inf:
      for next_city in range(num_city):
        if cost4transition[current_city, next_city] != np.inf:
          C[k, next_city] = min(
            C[k, next_city],
            C[k-1, current_city] + cost4transition[current_city, next_city]
            )

  return C

def func_cost_to_come(start_point=0, fixed_point=1):
    num_city = len(cost4transition[0])
    C = np.full((fixed_length, num_city), np.inf)
    C[0, initial] = 0
    for k in range(1, fixed_point):

        print(C)
        print()
        C = forward_value_iteration(k, C)

    return C


a, b, c, d, e = 0, 1, 2, 3, 4
initial = b
fixed_length =6




cost4transition = np.zeros((5,5))
cost4transition[:,:] = np.inf
cost4transition[a,a]=2
cost4transition[a,b]=2
cost4transition[b,c]=1
cost4transition[b,d]=4
cost4transition[c,a]=1
cost4transition[c,d]=1
cost4transition[d,c]=1
cost4transition[d,e]=1

num_city = len(cost4transition[0])
G = np.full((fixed_length, fixed_length), np.inf)
G[0, 3] = 0

G = func_cost_to_come(initial, fixed_length)
print(G)

[[inf  0. inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [inf inf  1.  4. inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [inf inf  1.  4. inf]
 [ 2. inf  5.  2.  5.]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [inf inf  1.  4. inf]
 [ 2. inf  5.  2.  5.]
 [ 4.  4.  3.  6.  3.]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [inf inf  1.  4. inf]
 [ 2. inf  5.  2.  5.]
 [ 4.  4.  3.  6.  3.]
 [ 4.  6.  5.  4.  7.]
 [inf inf inf inf inf]]

[[inf  0. inf inf inf]
 [inf inf  1.  4. inf]
 [ 2. inf  5.  2.  5.]
 [ 4.  4.  3.  6.  3.]
 [ 4.  6.  5.  4.  7.]
 [ 6.  6.  5.  6.  5.]]
