In [2]:
# 1. unfixed-length planning
# a cost to go

import numpy as np

def UF_backward_value_iteration(G):

  num_city = len(cost4transition[0])
  #이전비용을 저장해둘 임시 G
  temp = G.copy()

  for current_city in range(num_city):
    if G[current_city] != np.inf:
        for prev_city in range(num_city):
            if cost4transition[prev_city, current_city] != np.inf:
              G[prev_city] = min(
                G[prev_city],
                temp[current_city] + cost4transition[prev_city, current_city]
                )

  return G

def UF_func_cost_to_go(end_point):
  # Initialization
  num_city = len(cost4transition[0])
  G = np.full(num_city, np.inf)
  G[goal] = 0
  while True:
    G_pre = G.copy()
    print(G)
    print()
    G = UF_backward_value_iteration(G)

    if np.array_equal(G_pre, G):
      break
  return G




a, b, c, d, e = 0, 1, 2, 3, 4
goal = b


cost4transition = np.zeros((5,5))
cost4transition[:,:] = np.inf
cost4transition[a,a]=2
cost4transition[a,b]=2
cost4transition[b,c]=1
cost4transition[b,d]=4
cost4transition[c,a]=1
cost4transition[c,d]=1
cost4transition[d,c]=1
cost4transition[d,e]=1

num_city = len(cost4transition[0])
G = np.full(num_city, np.inf)
G[3] = 0

G = UF_func_cost_to_go(goal)
print(G)




[inf  0. inf inf inf]

[ 2.  0. inf inf inf]

[ 2.  0.  3. inf inf]

[ 2.  0.  3.  4. inf]

[ 2.  0.  3.  4. inf]


In [ ]:
import numpy as np

def UF_forward_value_iteration(C):

  num_city = len(cost4transition[0])

  temp = C.copy()


  for current_city in range(num_city):
    if C[current_city] != np.inf:
      for next_city in range(num_city):
        if cost4transition[current_city, next_city] != np.inf:
          C[next_city] = min(
            C[next_city],
            temp[current_city] + cost4transition[current_city, next_city]
            )

  return C

def UF_func_cost_to_come(start_point):
  # Initialization
  num_city = len(cost4transition[0])
  C = np.full(num_city, np.inf)
  C[start_point] = 0
  while True:
    C_pre = C.copy()
    print(C)
    print()
    C = UF_forward_value_iteration(C)
    if np.array_equal(C_pre, C):
      break
  return C


a, b, c, d, e = 0, 1, 2, 3, 4
initial = b
fixed_length =6

num_city = len(cost4transition[0])
G = np.full((fixed_length, fixed_length), np.inf)
G[0, 3] = 0


cost4transition = np.zeros((5,5))
cost4transition[:,:] = np.inf
cost4transition[a,a]=2
cost4transition[a,b]=2
cost4transition[b,c]=1
cost4transition[b,d]=4
cost4transition[c,a]=1
cost4transition[c,d]=1
cost4transition[d,c]=1
cost4transition[d,e]=1

G = UF_func_cost_to_come(initial)
print(G)

[inf  0. inf inf inf]

[inf  0.  1.  4. inf]

[2. 0. 1. 2. 5.]

[2. 0. 1. 2. 3.]

[2. 0. 1. 2. 3.]
